# Generated by Django 6.0 on 2026-05-31 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lyrics", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="song",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
